# docker-compose for financial api planner
# set the name of the project environment - if required
version: "3.8"

services:

  db:

    image: mcr.microsoft.com/mssql/server:2019-latest

    container_name: database

    ports:
      - "14330:1433"

    environment:
      ACCEPT_EULA: Y # as if you'd a choice
      SA_PASSWORD: yourStrong(!)Password
